### PR TITLE
Lock and update dependencies

### PR DESCRIPTION
**Pull request by epreston**
This change updates dependencies but locks two important ones until fixes are submitted.

- locks playcanvas to 1.64.4 until shader is updated (breaks in 1.65)
- locks lint config to 1.5.0 until "requiring .ts extension" on imports is supported with changes to the build system.

Supports: #229

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by willeastcott** [comment]
We need to figure out what to do with the import extension rule. We want extensions for ESM and no extensions for TS.

**Comment by epreston** [comment]
I'll look at the rules and see if we can add `{ "ts": "never" }`

**Comment by epreston** [comment]
I can fix in the project overriding the rule.  Want PR on pc-eslint-config ?

```json
  "eslintConfig": {
    "rules": {
      "import/extensions": ["error", "always", { "ts": "never" }],
    }
  },
```

**Comment by willeastcott** [comment]
Yes please!

**Comment by epreston** [comment]
I'll test.  JSX and JSON are listed separately so guessing it will need to be explicit.

**Comment by epreston** [comment]
Yep, the following sorts out "ts" and "tsx"
```
"import/extensions": ["error", "always", { "ts": "never", "tsx": "never" }],
```

**Comment by willeastcott** [comment]
OK, new eslint config is published to NPM as 1.7.1

**Comment by epreston** [comment]
Cool. We merge this and I build PR to unlock it again and update ?

**Comment by epreston** [comment]
Incoming PRs.

**Pull request merged**
