### PR TITLE
Changed glTF Viewer to Model Viewer in readme, package and index.html

### PR DESCRIPTION
**Pull request by yaustar**
I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by slimbuck — APPROVED** [review]

**Comment by slimbuck** [comment]
Actually... thinking through this a little more, we probably don't want to remove the glTF part. Most people will be searching for 'gltf viewer' and we'd not want to lose out there.

**Comment by yaustar** [comment]
Do we want to add that to the index.html title and package.json? I left GLTF in the description of the of the readme

eg PlayCanvas glTF Model Viewer?

**Comment by slimbuck** [comment]
> Do we want to add that to the index.html title and package.json? I left GLTF in the description of the of the readme
> 
> eg PlayCanvas glTF Model Viewer?

Not really sure what's best... @willeastcott ?

**Comment by willeastcott** [comment]
To be honest, I wouldn't change any of this for the time being. We decided to change the URL and repo name to `model-viewer` but it's still a glTF viewer (primarily).

**Comment by yaustar** [comment]
Not a problem, closing

**Pull request closed without merging**
