### PR TITLE
Fix path to PCUI in tsconfig.json

### PR DESCRIPTION
**Pull request by willeastcott**
Fix Intellisense errors related to PCUI React components. Also remove an unused import.

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Review by kpal81xd — APPROVED** [review]

**Comment by kpal81xd** [comment]
@willeastcott is this good to merge?

**Comment by willeastcott** [comment]
I'm gonna say.....yeeeeessss? :scared:

**Comment by kpal81xd** [comment]
> I'm gonna say.....yeeeeessss? 😨

Ill let you merge it in 😅

**Comment by willeastcott** [comment]
🐔

**Pull request merged**
