### PR TITLE
Camera controls rework

### PR DESCRIPTION
**Pull request by kpal81xd**
- Rewrote orbit camera to use pointer events
- Changed right click to orbit around camera (instead of focal point)
- Changed pan to be middle mouse button/holding shift and right click to drag
- Added smoothing to flying, orbiting, zooming and panning (frame rate invariant)
- Fixed panning (doesnt rotate around camera)

https://github.com/playcanvas/model-viewer/assets/48248865/802e5c91-164a-49de-8da3-5d2eb4f1b11e

I confirm I have signed the [Contributor License Agreement](https://docs.google.com/a/playcanvas.com/forms/d/1Ih69zQfJG-QDLIEpHr6CsaAs6fPORNOVnMv5nuo0cjk/viewform).

### CODE REVIEW

**Comment by slimbuck** [comment]
Did a quick local test and have a few comments:
- i personally don't like having to switch between the two camera types (and not sure what the win is compared to before)
- orbit camera has no smoothing
- orbit camera right mouse button should pan the camera (currently both left and right buttons orbit the camera).
- mouse scroll zoom is inverted
- frame function resets the camera orientation. it should just move the camera (not rotate it) to frame the current selection. should also have smoothing.
- fly camera rotation isn't smoothed
- i much prefer the distance-based zooming, with smoothing

**Comment by kpal81xd** [comment]
> Did a quick local test and have a few comments:
> 
> * i personally don't like having to switch between the two camera types (and not sure what the win is compared to before)
> * orbit camera has no smoothing
> * orbit camera right mouse button should pan the camera (currently both left and right buttons orbit the camera).
> * mouse scroll zoom is inverted
> * frame function resets the camera orientation. it should just move the camera (not rotate it) to frame the current selection. should also have smoothing.
> * fly camera rotation isn't smoothed
> * i much prefer the distance-based zooming, with smoothing

Added all changes!

**Comment by slimbuck** [comment]
Did another quick test:
- 'F' to frame doesn't frame meshes correctly
- dragging any slider on setting popup rotates the camera (check FOV, for example)
- panning the camera doesn't seem to go perpendicular to screen
- panning sensitivity doesn't seem to follow orbit distance (zooming closer in should result in less sensitive panning)
- zooming all the way in to focus point seems to go too far (goes through the target surface)
- zoom button is now very sensitive on my mouse

**Review by slimbuck — APPROVED** [review]
Awesome! Just a tiny issue with framing then we're good to GO!

**Pull request merged**
